### PR TITLE
Move to newest oauth-proxy container

### PR DESCRIPTION
**Pull request by csibbitt**
* Moved definitions to "Related Images"

### CODE REVIEW

**Comment by csibbitt** [comment]
See https://github.com/infrawatch/service-telemetry-operator/pull/420#issuecomment-1503774016 for comments about the build errors.

**Comment by csibbitt** [comment]
This builds and passes tests locally using the STO CI Ansible 
```
$ ansible-playbook --extra-vars __local_build_enabled=true --extra-vars working_branch=csibbitt-STF-1290-new-oauth-with-bcrypt --extra-vars __service_telemetry_snmptraps_enabled=true --extra-vars __service_telemetry_storage_ephemeral_enabled=true ./build/run-ci.yaml
[...]
* [info] CI Build complete. You can now run tests.

$ oc describe po default-cloud1-coll-meter-smartgateway-5b5b7866bd-tw984 | grep -A 1 oauth-proxy
  oauth-proxy:
    Container ID:  cri-o://9bacfc174124ac6e693431d6163d3acdbf041cf984a3cf4b929cdc0167c0815b
    Image:         quay.io/openshift/origin-oauth-proxy:latest

$ ./tests/smoketest/smoketest.sh 
[...]
*** [SUCCESS] Smoke test job completed successfully
```

**Review by leifmadsen — COMMENTED** [review]
Looks like you'll probably make the same/similar changes to the Dockerfile here once it's sorted on the STO repo. Otherwise, this all looks pretty good to me. Just ping when you have a final setup and are looking for approval.

**Comment by csibbitt** [comment]
> Looks like you'll probably make the same/similar changes to the Dockerfile here once it's sorted on the STO repo. Otherwise, this all looks pretty good to me. Just ping when you have a final setup and are looking for approval.

It turns out that these packages aren't even necessary in this container, I just did it reflexively. Only STO uses the `password_hash("bcrypt")` call that needs these.

**Pull request merged**
