### PR TITLE
[zuul] Add zuul job to SGO

### PR DESCRIPTION
**Pull request by elfiesmelfie**
Depends-On: http://github.com/infrawatch/service-telemetry-operator/pull/512

### CODE REVIEW

**Comment by elfiesmelfie** [comment]
recheck

**Comment by elfiesmelfie** [comment]
recheck

Updated infrawatch/service-telemetry-operator#512 to use explicit reference to sto_dir

**Review by csibbitt — APPROVED** [review]

**Review by leifmadsen — APPROVED** [review]

**Comment by elfiesmelfie** [comment]
recheck
it looks like the github-check pipeline didn't run last time

**Comment by elfiesmelfie** [comment]
> recheck it looks like the github-check pipeline didn't run last time

Okay, I'm pretty sure this isn't running because there's no config on master.

**Comment by leifmadsen** [comment]
> > recheck it looks like the github-check pipeline didn't run last time
> 
> Okay, I'm pretty sure this isn't running because there's no config on master.

That actually sounds familiar from the STO side of things. I think we just "sent it" to get the initial configuration there.

**Pull request merged**
